### ISSUE TITLE
move constants to namespace

### ISSUE THREAD

**Issue by dstroy0** [dstroy0/InputHandler#57]
ih_constants:: makes sense as a name to me, unless you have any ideas?

all the lib constants should go in here

**Comment by 2bndy5** [comment]
It may get a bit "wordy" if the namespace is repeated in the namespace's members.
```cpp
namespace InputHandler {

const char* InputHandlerConst = "";

}
```
which would be referenced as `InputHandler::InputHandlerConst`.

Otherwise, namespaces are a great habit! In python, each module is a namespace 😉

**Comment by dstroy0** [comment]
yes, I would shorten the names significantly, I just need to test that it works correctly.  I did some preliminary testing to make sure that the members actually ended up in progmem.

**Comment by dstroy0** [comment]
Just doing some regression testing and then I'll add the other members.

**Comment by dstroy0** [comment]
Looks like there's a separate preprocessor issue for mbed platforms.

**Comment by dstroy0** [comment]
constants are in their own namespace
