### ISSUE TITLE
build binaries workflows

### ISSUE THREAD

**Issue by dstroy0** [dstroy0/InputHandler#61]
Dependency adventures!  Linux is fun!

**Comment by dstroy0** [comment]
Just trying to get rid of the WARNINGS in the build logs.

**Comment by dstroy0** [comment]
Then I'll worry about saving the built binary.

**Comment by dstroy0** [comment]
it looks like it's building with no warnings, I'll figure out how to save it to the repo and test it tomorrow

**Comment by dstroy0** [comment]
Ok now I just need to figure out how to push the changes in the CI.

**Comment by dstroy0** [comment]
Ok, I cloned the main branch into release and protected release so this workflow should finish correctly now, just waiting on it now.

**Comment by 2bndy5** [comment]
Apparently, the `set-output` command is now deprecated in GitHub action workflows. They recommend using a new variable in the github env file: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

**Comment by dstroy0** [comment]
Yeah, some external actions are using `set-output`.

**Comment by 2bndy5** [comment]
yeah, we plan to migrate the cpp-linter action to the env file approach soon.

**Comment by dstroy0** [comment]
It looks like this is fixed.  I want to tweak the CI a bit more but this is working fine.  A build happens on push to tools/cli_gen_src that targets tools/bin/latest and one on release to tools/bin/release.

**Comment by 2bndy5** [comment]
There is a way to upload build artifact from the CI to a published release's assets (which by default is just a zip and tar.gz files containing a snapshot of the repo at the tagged commit): see [csexton/release-asset-action](https://github.com/csexton/release-asset-action).

I often upload my CI build artifacts using [actions/upload-artifact](https://github.com/actions/upload-artifact)
